FROM golang:1.16-buster as build

WORKDIR /base
ADD . /base/
RUN go build -o /base/app ./cmd/destination-go-example

FROM gcr.io/distroless/base-debian10:debug
COPY --from=build /base/app /base/app

LABEL io.airbyte.version=0.0.1
LABEL io.airbyte.name=airbyte/destination-go-example

ENTRYPOINT ["/base/app"]
